### ISSUE TITLE
questions about pre-trained visual representations

### ISSUE THREAD

**Issue by JacksonYeeeee** [zhangxi1997/MCC#1]
Can I get a download link for pre-trained visual representaions? If not, could you please give more details about generating them?

**Comment by zhangxi1997** [comment]
Thanks, please refer to [https://github.com/Deanplayerljx/tab-vcr/tree/master/data](tab-vcr) to download the visual features.
Note that we use the attribute features instead of the new_tag features.

**Comment by zhangxi1997** [comment]
> Can I get a download link for pre-trained visual representaions? If not, could you please give more details about generating them?

Thanks, please refer to [tab-vcr](https://github.com/Deanplayerljx/tab-vcr/tree/master/data) to download the visual features.
Note that we use the attribute features instead of the new_tag features.

**Comment by JacksonYeeeee** [comment]
> > Can I get a download link for pre-trained visual representaions? If not, could you please give more details about generating them?
> 
> Thanks, please refer to [tab-vcr](https://github.com/Deanplayerljx/tab-vcr/tree/master/data) to download the visual features. Note that we use the attribute features instead of the new_tag features.

Thank you.
